name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'pull_request' }}

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo test
        run: cargo test --all --locked --verbose

      - name: cargo build
        run: cargo build --all --locked --verbose

